# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3215de4ce6d165e0d4700973cb2c033"
application_url = "https://necessarily-slight-guns-das.trycloudflare.com"
embedded = true
name = "test-dev-app2"
handle = "test-dev-app2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping"

[auth]
redirect_urls = [
  "https://necessarily-slight-guns-das.trycloudflare.com/auth/callback",
  "https://necessarily-slight-guns-das.trycloudflare.com/auth/shopify/callback",
  "https://necessarily-slight-guns-das.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
